name: Daily Sonar Scan
on:
  schedule:
    - cron: '0 5 * * 1-5'
  workflow_dispatch:

jobs:
  sonar:
    name: Daily Sonar Scan
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore .NET dependencies
        run: |
          dotnet restore
  
      - name: Restore Tools
        run: |
          dotnet tool restore

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: hesbps.azurecr.io
          username: ${{ secrets.ACR_DOCKER_USER }}
          password: ${{ secrets.ACR_DOCKER_PAT }}

      - name: SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner begin /k:"bpsafrica_hes"  /o:"bpsafrica" /d:sonar.token="$SONAR_TOKEN" /d:"sonar.dotnet.excludeTestProjects=true" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
          dotnet build --configuration Release --no-incremental
          dotnet tool run dotnet-coverage collect "dotnet test --configuration Release --no-build" -f xml -o "coverage.xml"
          dotnet sonarscanner end /d:sonar.token="$SONAR_TOKEN"
